language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

before_install:
  # Install Kafka
  - wget http://www.us.apache.org/dist/kafka/0.8.2.1/kafka_2.10-0.8.2.1.tgz -O kafka.tgz
  - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  - cd kafka
  # Run Zookeeper/Kafka on localhost (default ports for ZK, Kafka: 2181, 9092)
  - ./bin/zookeeper-server-start.sh config/zookeeper.properties &
  - sleep 3
  - ./bin/kafka-server-start.sh config/server.properties &
  - sleep 5

script:
  - cargo build --release --all --verbose
  - cargo test --release --all --verbose

matrix:
  allow_failures:
    - rust: stable
    - rust: beta
