[package]
name = "event-handler"
version = "0.1.0"
authors = ["Mike Lubinets <lubinetsm@yandex.ru>"]
edition = "2018"

[dependencies]
rustyrobot = { path = "../common" }
rdkafka = "0.17.0"
ctrlc = "3.1.1"
failure = "0.1.2"
log = "0.4.5"
fern = "0.5.6"
chrono = "0.4.6"